$text_color = rgba(ffdad4FF)
$entry_background_color = rgba(40020011)
$entry_border_color = rgba(a38e6e55)
$entry_color = rgba(ffdad4FF)
$font_family = JetBrains Mono
$font_family_clock = JetBrains Mono
$font_material_symbols = Symbols Nerd Font
