[mgr]
linemode = "size"

[opener]
imv_open = [
	{ run = "imv -n %s1 %d1", desc = "Open" },
]

[open]
prepend_rules = [
	{ mime="image/*", use = [ "imv_open", "reveal" ] },
    { url = "*.html", use = [ "open", "edit" ] }
]
