general {
    lock_cmd = pidof hyprlock || hyprlock --no-fade-in --immediate-render # avoid starting multiple hyprlock instances.
    # Need this fix if session locks after wakeup, not before: 
    # https://github.com/hyprwm/hypridle/issues/146#issuecomment-2961021929
    before_sleep_cmd = loginctl lock-session                 # lock before suspend.
    after_sleep_cmd = swaymsg "output * power on"            # to avoid having to press a key twice to turn on the display.
}

# pidof hyprlock is used so that this listener will not fire when the screen
# is locked
listener { 
    timeout = 65
    on-timeout = pidof hyprlock || brightnessctl -sd 'tpacpi::kbd_backlight' set 0 # turn off keyboard backlight.
    on-resume = pidof hyprlock || brightnessctl -rd 'tpacpi::kbd_backlight'        # turn on keyboard backlight.
}

# pidof hyprlock is used so that this listener will not fire when the screen
# is locked
listener {
    timeout = 60
    on-timeout = pidof hyprlock || (chayang -d 5 && swaymsg "output * power off" && loginctl lock-session)
    on-resume = swaymsg "output * power on"
}


# This handles "Manual Lock".
listener {
    timeout = 10
    # Logic: If hyprlock IS running -> Turn power & backlight OFF
    on-timeout = pidof hyprlock && swaymsg "output * power off" && brightnessctl -sd 'tpacpi::kbd_backlight' set 0
    on-resume = pidof hyprlock && swaymsg "output * power on" && brightnessctl -rd 'tpacpi::kbd_backlight'
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
