general {
    lock_cmd = pidof hyprlock || hyprlock --no-fade-in --immediate-render # avoid starting multiple hyprlock instances.
    # Need this fix if session locks after wakeup, not before: 
    # https://github.com/hyprwm/hypridle/issues/146#issuecomment-2961021929
    before_sleep_cmd = loginctl lock-session                 # lock before suspend.
    after_sleep_cmd = swaymsg "output * power on"            # to avoid having to press a key twice to turn on the display.
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener { 
    timeout = 65
    on-timeout = brightnessctl -sd 'tpacpi::kbd_backlight' set 0 # turn off keyboard backlight.
    on-resume = brightnessctl -rd 'tpacpi::kbd_backlight'        # turn on keyboard backlight.
}

listener {
    timeout = 60
    on-timeout = chayang -d 5 && swaymsg "output * power off" && loginctl lock-session
    on-resume = swaymsg "output * power on"
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
